### PR TITLE
Fission is now default

### PR DESCRIPTION
**Pull request by tysmith**
Fission is now enabled by default.

### CODE REVIEW

**Comment by sylvestre** [comment]
I have been told that we are still using !fission for Android (TBC)

**Comment by tysmith** [comment]
In an email with @cpeterso he mentioned that non-fission code paths will be removed soon.

**Comment by sylvestre** [comment]
Ok please ignore me then :)

Le mar. 4 janv. 2022 à 00:28, Tyson Smith ***@***.***> a
écrit :

**Comment by cpeterso** [comment]
> I have been told that we are still using !fission for Android (TBC)

> In an email with @cpeterso he mentioned that non-fission code paths will be removed soon.

Oops. @sylvestre is correct! I forgot that we will keep testing non-Fission code paths on desktop Linux until we ship Android Fission. (We don't have the automation capacity to run all mochitests/etc on Android, so until we can ship Android Fission, we will run those tests in non-Fission mode on desktop Linux to find regressions in non-Fission code paths.) However, I don't know if that means we still need to fuzz non-Fission on desktop.

The ETA for shipping Android Fission is probably the end of 2022 Q2.

**Comment by tysmith** [comment]
We plan to fuzz with the `no-fission` variant with a few fuzzers for now.

**Pull request merged**
